### ISSUE TITLE
Generacion del token

### ISSUE THREAD

**Issue by tobiasbianchi** [Xero-Hige/DrTinder#45]
Crear token particular para cliente conectado y ponerle tiempo de vencimiento

**Comment by Xero-Hige** [comment]
Para el token lo mas fácil es hacer un concat de: `user`+`pass`+`timestamp` y hashearlo, por ejemplo con `MD5` (eventualmente se puede truncar a n caracteres). 
Para vencimiento, se tiene un `map<token,timestamp>` y la validez es desde `timestamp` hasta `timestamp+expire`.
Cuando llega un request, validas que el token este y no haya expirado antes de procesarla.
